_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# min_epochs: 1 # prevents early stopping
# max_epochs: 100
min_steps: 10
max_steps: 300000


accelerator: cpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# gradient_clip_val: 1000.

# how often to check the validation set, validating after N batches
val_check_interval: 2000

# perform a validation loop every N training epochs
check_val_every_n_epoch: null

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# Enable anomaly detection for the autograd engine
detect_anomaly: False
