defaults:
  - model_checkpoint.yaml
  # - early_stopping.yaml
  - model_summary.yaml
  - rich_progress_bar.yaml
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  monitor: "hp_metric"
  mode: "max"
  save_top_k: 3
  filename: "step_{step}_{bar:.4f}_{psnr:.4f}"
  save_last: True
  auto_insert_metric_name: False
