# @package _global_

defaults:
  - _self_
  - datamodule: duts_datamodule.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: object_watermark2.yaml
  - logger: tensorboard.yaml
  - trainer: gpu.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

seed: 42

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
