_target_: src.datamodules.DUTSDataModule
dataset_cfg:
  data_dir: ${paths.data_dir}/DUTS
  image_shape: [3, 256, 256]
  msg_len: 30
  # number of background images for each object, real batch size is the product of this and batch_size
  num_backgrounds: 1

dataloader_cfg:
  batch_size: 12
  num_workers: 4
  pin_memory: False
