_target_: src.datamodules.VOCDataModule
dataset_cfg:
  data_dir: ${paths.data_dir}/VOC2012/StandardObject/
  msg_len: ${model.msg_len}

dataloader_cfg:
  batch_size: 32
  num_workers: 4
  pin_memory: False
